### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by dandxy89** [dandxy89/ImageModels#1]
Image Models need a update and help to improve them.

**Comment by dandxy89** [comment]
ZFNet and AlexNet have been updated.

**Comment by dandxy89** [comment]
_Next steps:_

- Update the remaining script to the latest version of Keras
- Add a requirements file to indicate the version used of modules
- Acknowledge **_svjan_** on the main README

**Comment by alxy** [comment]
I am not sure what you did there, but it appears that the AlexNet model found in AlexNet.py is realy very wrong: https://github.com/dandxy89/ImageModels/blob/master/AlexNet.py#L108
You are using convolution kernel sizes of size 55x55 there. The new implementation looks much better though (y). YOu should realy consider removing it, as I have been using it (btw, you get around 145 mio trainable parameters with this architecture, but no usable results :p )

**Comment by dandxy89** [comment]
I never test them to be honest. The whole project needs an update.

**Comment by dandxy89** [comment]
There was a pull request that added two ipython notebooks. Can you review those?

**Comment by alxy** [comment]
The AlexNet (notebook) looks good to me. The original paper proposed a dual GPU approach, so most filter numbers have been doubbled in this implementation, but this is OK. I will actually test the architecture and can then give feedback if it works as expected.

**Comment by dandxy89** [comment]
Excellent - thanks in advance for the feedback Alex

**Comment by alxy** [comment]
@svjan5 I am trying to reproduce your results presented here: https://github.com/dandxy89/ImageModels/blob/master/AlexNet.ipynb

Can you tell, if you really used the original CIFAR-100 dataset, which consists of very small images (32x32px). Did you do any other kind of preprocessing other than upscaling them to 227x227? For me it appears as if the net does not learn anything at all. The loss sticks to a certain value, and the val_accuracy perfectly matches with accuracy by chance (1%).

**Comment by alxy** [comment]
Ok, I got it working now using the original ILSVRC ImageNet dataset. However, I did not get the reported results on the entire set (that is classification of 1000 categories) - it's more like 10% top-1 accuracy. 

The architecture still appears to be working.

**Comment by dandxy89** [comment]
Thanks Alexander.
