### ISSUE TITLE
Bug in KerasLayers/CustomLayer.py file

### ISSUE THREAD

**Issue by svjan5** [dandxy89/ImageModels#2]
I am unable to understand that why you are not passing `dim_ordering` information in the LRN2D (Custom layer) because if the user uses `DIM_ORDERING = 'tf'` instead of `DIM_ORDERING = 'th'` then the layer will surely return a wrong output.

`b, ch, r, c = K.shape(X)`
should be
`b, r, c, ch = K.shape(X)` in case backend is 'tf'

**Comment by dandxy89** [comment]
You're are right, it should be the other way around.

To be honest I wasn't aware anyone was using this project at all. I created all of this over a year ago and since then Keras has undergone a substantial change with the recent release of version 2.0.

**Comment by svjan5** [comment]
The code was also a part of main [Keras library ] (https://github.com/fchollet/keras/blob/97174dd298cf4b5be459e79b0181a124650d9148/keras/layers/normalization.py#L83) but now they have removed this layer. It seems like this layer is not used anymore by the community in practice. I am working on reproducing AlexNet results, therefore, I am looking for it.

Anyways, thanks a lot. With that line, there will be few more changes as well.

**Comment by dandxy89** [comment]
I'd appreciate the effort to update these - if you do create a revised version of AlexNet It would be great to include your version.

**Comment by svjan5** [comment]
Sure, I will try.

**Comment by svjan5** [comment]
Hi, I have made the changes but I am unable to create a pull request.

**Comment by dandxy89** [comment]
I think the simplest method of creating a pull request is to fork the current repo and then apply your changes to that. Once you've commit your changes, you should then be able to create a pull request using the website.

**Comment by svjan5** [comment]
Yes, that worked!
